export const FORUM_PROPOSALS_PAGE_SIZE = 10;
export const FORUM_PROPOSALS_SKELETON_COUNT = 3;
export const FORUM_PROPOSALS_LOAD_MORE_MIN_DELAY = 500;
export const ALL_FORUM_PROPOSAL_CATEGORIES = 'all';
export const FORUM_PROPOSAL_SIGNATURE_PREFIX = 'QLEAP:CREATE_PROPOSAL';
